POST http://localhost:3001/api/blogs 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodWRlbiIsImlkIjoiNjdiYzIyZWNkZGIyYzcwZTU3Y2E4MmQzIiwiaWF0IjoxNzQwNDkzNTUxLCJleHAiOjE3NDA0OTcxNTF9.PT3u68hhQf5JhgwdFSFhZe3HdKClsZKjtJeJ4eHImMw
Content-Type: application/json

{
    "title": "My blogNew11111",
    "author": "Some author",
    "url": "http://www.myblognew.fi",
    "likes": 999
}