POST http://localhost:3001/api/blogs 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodWRlbiIsImlkIjoiNjdjMmRkZDdiYTY1MzVmMTJjZjk2ZGIxIiwiaWF0IjoxNzU2MTI1OTE1LCJleHAiOjE3NTYxMjk1MTV9.BuNjXDvubMoWpE1HfA_bIWv8u6EYP869tLLSK4xWve4
Content-Type: application/json

{
    "title": "Books",
    "author": "Denis",
    "url": "http://www.books.fi",
    "likes": 15
}