POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "title": "My blog",
    "author": "Some author",
    "url": "http://www.myblog.fi",
    "likes": 8,
    "userId": "67bc22ecddb2c70e57ca82d3"
}