DELETE http://localhost:3001/api/blogs/67bdbf28b7e0e6ff7aea00f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjY3YmRiYjA1OThlMGFkNjIyMDRhNmE2NyIsImlhdCI6MTc0MDQ4ODUxNiwiZXhwIjoxNzQwNDkyMTE2fQ.LFiBl0TLOc1TK1fmqpwGRX_fSqf2fm1PknnDb0xJ8iE
Content-Type: application/json