DELETE http://localhost:3001/api/blogs/67bdd303ea6c0e146484a905
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodWRlbiIsImlkIjoiNjdiYzIyZWNkZGIyYzcwZTU3Y2E4MmQzIiwiaWF0IjoxNzQwNDkzNTUxLCJleHAiOjE3NDA0OTcxNTF9.PT3u68hhQf5JhgwdFSFhZe3HdKClsZKjtJeJ4eHImMw
Content-Type: application/json