PUT http://localhost:3001/api/blogs/67bdebbd81c8fff70f4566ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodWRlbiIsImlkIjoiNjdiZGViMWM4MWM4ZmZmNzBmNDU2NmE3IiwiaWF0IjoxNzQwNDk5ODExLCJleHAiOjE3NDA1MDM0MTF9.JNfSP2SkM0fpFb8jRZaw3liks8dxAPp7adR6TaYd7cA
Content-Type: application/json

{
  "title": "Ice Fishing",
  "author": "Denis Chuvakov",
  "url": "https://icefishing.com",
  "likes": 100
}