PUT http://localhost:3001/api/blogs/691cdf0757926e6790e9b368
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNodWRlbiIsImlkIjoiNjdjMmRkZDdiYTY1MzVmMTJjZjk2ZGIxIiwiaWF0IjoxNzYzNTA0NTM1LCJleHAiOjE3NjM1MDgxMzV9.wgdNHsFYOABi6IGL2YkG0q_7WtHuxEI3RuvgT4fwRec
Content-Type: application/json

{
  "title": "gnbghngf",
  "author": "ussseeeer1",
  "url": "sadasda",
  "likes": 10
}